#!/usr/bin/python3
import os
import sys
genFilesDir=#gengendirdir




def require():
	lib=input("Enter lib/file name:	")
	app=open("app.js","r").read()
	app=app.replace("//requirements $gengen","var "+ lib +"= require('"+lib+"');"+"\n//requirements $gengen")
	open("app.js","w").write(app)
	save=input("third party lib??? (y/n)(default=y): ")
	if save in ['n','N','no','NO','No']:
		print("done")
		return
	os.system("npm install --save "+lib)
	print("done")


def addMongoose():  
	dbName=input("Enter db name:	")
	if os.path.exists("app.js"):
		app=open("app.js","r").read()
		mongoose=open(genFilesDir+"mongoose.js","r").read()
		mongoose=mongoose.replace("dbName",dbName)
		app=app.replace("//mongodb setup $gengen",mongoose)
		app=app.replace("//requirements $gengen","var mongoose = require('mongoose');"+"\n//requirements $gengen")
		open("app.js","w").write(app)
		os.system("npm install --save mongoose")
	else:
		print("app.js not found")
		exit(1)
	print("Done")


def ModifiedApp():
	sure=input("Are you sure this will delete your app.js (y/n)(default=y): ")
	if sure in ['n','N','no','NO','No']:
		print("cancelled")
		return
	if os.path.exists("app.js"):
		newApp=open(genFilesDir+"app.js","r").read()
		open("app.js","w").write(newApp)
	else:
		print("app.js not found")
		exit(1)
	print("Done")


def addModel():
	modelName=input("Enter the model name:	")
	if os.path.exists("app.js")==False:
		print("wrong path!!!!!")
		exit(1)
	if os.path.exists("models")==False:
		os.mkdir("models")
	model=open(genFilesDir+"model.js","r").read()
	model=model.replace("SName",modelName)
	newModel=open("models/"+modelName+".js","w")
	newModel.write(model)
	print("Done")	


def addNewPage():
	pageName=input("Enter the page name:	")
	if os.path.exists("app.js"):
		#modifying 	app.js
		newApp=open("app.js","r").read()
		newApp=newApp.replace("//requirements $gengen","var "+pageName+"Router = require('./routes/"+pageName+"');"+"\n//requirements $gengen")
		newApp=newApp.replace("//pages $gengen","app.use('/"+ pageName+"', "+pageName+"Router);"+"\n//pages $gengen")
		open("app.js","w").write(newApp)
		#creating ejs file
		ejsFile=open(genFilesDir+"page.html","r").read()
		ejsFile=ejsFile.replace("pageName",pageName)
		open("views/"+pageName+".ejs","w").write(ejsFile)	
		#creating the router file
		routerFile=open(genFilesDir+"router.js","r").read()
		routerFile=routerFile.replace("pageName",pageName)
		open("routes/"+pageName+".js","w").write(routerFile)
	else:
		print("app.js not found")
		exit(1)
	print("Done")




functions=[ModifiedApp,addMongoose,addModel,addNewPage,require,exit]

if len(sys.argv)==2:
	option=int(sys.argv[1])-1	
	functions[option]()

else:
	print('''
	Make programming fun again!!!!!!
	1: reconstruct the app.js file
	2: add mongoose support
	3: generate mongodb model
	4: Add new page
	5: require new library/file
	0: exit
	''')


	option=int(input("input:	"))-1
	functions[option]()
